import { Language } from './types';

export const PRAYERS = ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'] as const;

export const SURAHS = [
  "Al-Fatihah", "Al-Baqarah", "Aal-E-Imran", "An-Nisa", "Al-Ma'idah", "Al-An'am", "Al-A'raf", "Al-Anfal", "At-Tawbah", "Yunus",
  "Hud", "Yusuf", "Ar-Ra'd", "Ibrahim", "Al-Hijr", "An-Nahl", "Al-Isra", "Al-Kahf", "Maryam", "Ta-Ha",
  "Al-Anbiya", "Al-Hajj", "Al-Mu'minun", "An-Nur", "Al-Furqan", "Ash-Shu'ara", "An-Naml", "Al-Qasas", "Al-Ankabut", "Ar-Rum",
  "Luqman", "As-Sajdah", "Al-Ahzab", "Saba", "Fatir", "Ya-Sin", "As-Saffat", "Sad", "Az-Zumar", "Ghafir",
  "Fussilat", "Ash-Shura", "Az-Zukhruf", "Ad-Dukhan", "Al-Jathiyah", "Al-Ahqaf", "Muhammad", "Al-Fath", "Al-Hujurat", "Qaf",
  "Adh-Dhariyat", "At-Tur", "An-Najm", "Al-Qamar", "Ar-Rahman", "Al-Waqi'ah", "Al-Hadid", "Al-Mujadilah", "Al-Hashr", "Al-Mumtahanah",
  "As-Saff", "Al-Jumu'ah", "Al-Munafiqun", "At-Taghabun", "At-Talaq", "At-Tahrim", "Al-Mulk", "Al-Qalam", "Al-Haqqah", "Al-Ma'arij",
  "Nuh", "Al-Jinn", "Al-Muzzammil", "Al-Muddaththir", "Al-Qiyamah", "Al-Insan", "Al-Mursalat", "An-Naba", "An-Nazi'at", "Abasa",
  "At-Takwir", "Al-Infitar", "Al-Mutaffifin", "Al-Inshiqaq", "Al-Buruj", "At-Tariq", "Al-A'la", "Al-Ghashiyah", "Al-Fajr", "Al-Balad",
  "Ash-Shams", "Al-Layl", "Ad-Duha", "Ash-Sharh", "At-Tin", "Al-Alaq", "Al-Qadr", "Al-Bayyinah", "Az-Zalzalah", "Al-Adiyat",
  "Al-Qari'ah", "At-Takathur", "Al-Asr", "Al-Humazah", "Al-Fil", "Quraysh", "Al-Ma'un", "Al-Kawthar", "Al-Kafirun", "An-Nasr",
  "Al-Masad", "Al-Ikhlas", "Al-Falaq", "An-Nas"
];

export interface MultiLangHadith {
  arabic: string;
  en: string;
  ml: string;
  ta: string;
  ar: string;
  reference: string;
}

export const HADITHS: MultiLangHadith[] = [
  {
    arabic: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ",
    en: "The best among you are those who learn the Qur'an and teach it.",
    ml: "നിങ്ങളിൽ ഉത്തമൻ ഖുർആൻ പഠിക്കുകയും അത് മറ്റുള്ളവർക്ക് പഠിപ്പിച്ചു കൊടുക്കുകയും ചെയ്യുന്നവനാണ്.",
    ta: "உங்களில் சிறந்தவர் குர்ஆனைக் கற்றுக்கொண்டு அதைப் பிறருக்குக் கற்பிப்பவரே ஆவார்.",
    ar: "خيركم من تعلم القرآن وعلمه.",
    reference: "Sahih al-Bukhari 5027"
  },
  {
    arabic: "الطُّهُورُ شَطْرُ الإِيمَانِ",
    en: "Purity is half of faith.",
    ml: "ശുദ്ധി വിശ്വാസത്തിന്റെ പകുതിയാണ്.",
    ta: "சுத்தம் ஈமானின் (விசுவாசத்தின்) பாதியாகும்.",
    ar: "الطهور شطر الإيمان.",
    reference: "Sahih Muslim 223"
  },
  {
    arabic: "الدِّينُ النَّصِيحَةُ",
    en: "Religion is sincere advice.",
    ml: "മതം ഗുണകാംക്ഷയാണ്.",
    ta: "மார்க்கம் என்பது நற்போதனையாகும்.",
    ar: "الدين النصيحة.",
    reference: "Sahih Muslim 55"
  },
  {
    arabic: "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ",
    en: "Actions are but by intentions.",
    ml: "കർമ്മങ്ങൾ ഉദ്ദേശ്യങ്ങളെ അടിസ്ഥാനപ്പെടുത്തിയാണ്.",
    ta: "செயல்கள் அனைத்தும் எண்ணங்களைப் பொறுத்தே அமைகின்றன.",
    ar: "إنما الأعمال بالنيات.",
    reference: "Sahih al-Bukhari 1"
  },
  {
    arabic: "أَحَبُّ الأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ",
    en: "The most beloved of deeds to Allah are those that are most consistent, even if they are small.",
    ml: "അല്ലാഹുവിന് ഏറ്റവും പ്രിയപ്പെട്ട അമൽ കുറവാണെങ്കിലും സ്ഥിരമായി ചെയ്യുന്നതാണ്.",
    ta: "அல்லாஹ்வுக்கு மிகவும் விருப்பமான செயல் சிறியதாக இருந்தாலும் தொடர்ந்து செய்யப்படுவதே ஆகும்.",
    ar: "أحب الأعمال إلى الله أدومها وإن قل.",
    reference: "Sahih al-Bukhari 6464"
  },
  {
    arabic: "لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ",
    en: "None of you will believe until you love for your brother what you love for yourself.",
    ml: "താൻ ഇഷ്ടപ്പെടുന്നത് തന്റെ സഹോദരനും ഇഷ്ടപ്പെടുന്നത് വരെ നിങ്ങളിലാരും പൂർണ്ണ വിശ്വാസിയാവുകയില്ല.",
    ta: "உங்களில் ஒருவர் தனக்கு விரும்புவதையே தன் சகோதரனுக்கும் விரும்பும் வரை அவர் (முழுமையான) இறைநம்பிக்கையாளர் ஆக முடியாது.",
    ar: "لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه.",
    reference: "Sahih al-Bukhari 13"
  },
  {
    arabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ",
    en: "Whoever believes in Allah and the Last Day, let him speak goodness or remain silent.",
    ml: "അല്ലാഹുവിലും അന്ത്യദിനത്തിലും വിശ്വസിക്കുന്നവൻ നല്ലത് സംസാരിക്കട്ടെ, അല്ലെങ്കിൽ മിണ്ടാതിരിക്കട്ടെ.",
    ta: "அல்லாஹ்வையும் மறுமை நாளையும் நம்புபவர் நல்லதைப் பேசட்டும் அல்லது வாய்மூடி இருக்கட்டும்.",
    ar: "من كان يؤمن بالله واليوم الآخر فليقل خيرا أو ليصمت.",
    reference: "Sahih al-Bukhari 6018"
  }
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    welcome: 'Welcome',
    welcomeSub: 'Welcome to Ibadathi – Your Companion in Worship',
    selectLanguage: 'Choose your preferred language',
    getStarted: 'Get Started',
    login: 'Login',
    register: 'Register',
    username: 'Username',
    usernameAvailable: 'Username available',
    usernameTaken: 'Username already taken',
    suggestions: 'Suggestions:',
    name: 'Full Name',
    age: 'Age',
    sex: 'Gender',
    male: 'Male',
    female: 'Female',
    place: 'Place',
    password: 'Password',
    language: 'Language',
    home: 'Home',
    fard: 'Fard Prayers',
    qadah: 'Worship Calendar',
    sunnah: 'Sunnah Prayers',
    fasting: 'Fasting Tracker',
    quran: 'Quran Tracker',
    dhikr: 'Dhikr Counter',
    challenge: 'Dhikr Challenge',
    personal: 'Personal Dhikr',
    womensSpace: "Women's Space",
    haydMode: 'Hayd / Nifas Mode',
    active: 'Active',
    inactive: 'Inactive',
    completed: 'Completed',
    missed: 'Missed',
    excused: 'Excused',
    pending: 'Pending',
    save: 'Save',
    reset: 'Reset',
    lastRead: 'Last Read',
    surah: 'Surah',
    ayah: 'Ayah',
    juz: 'Juz',
    target: 'Target',
    progress: 'Progress',
    missedPrayers: 'Missed Prayers',
    back: 'Back',
    hadithTitle: 'Hadith of the Day',
    qibla: 'Qibla Finder',
    remembranceVerse: "Verily, in the remembrance of Allah do hearts find rest.",
    quranVirtue: "Virtues of Recitation",
    nextPrayer: 'Next Prayer',
    notificationOn: 'Notifications On',
    notificationOff: 'Notifications Off',
    prayerAlertBody: 'It is time for {prayer} prayer.',
    prayerAlertTitle: 'Ibadathi Prayer Alert',
    fajr: 'Fajr',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    todayPrayers: 'Today\'s Timings',
    qadaReminders: 'Qada Reminders',
    addReminder: 'Add Reminder',
    qadaAlertTitle: 'Qada Prayer Reminder',
    qadaAlertBody: 'Time to make up your missed prayers.',
    time: 'Time',
    reminders: 'Reminders',
    history: 'History',
    noHistory: 'No history yet',
    completeAndArchive: 'Archive Challenge',
    archiveSuccess: 'Challenge archived successfully!',
    markAllCompleted: 'Mark All Done',
    markAllMissed: 'Mark All Missed',
    dhikrList: 'Active Challenges',
    dhikrSalawat: 'Salawat on the Prophet ﷺ',
    dhikrSubhanAllah: 'SubhanAllah',
    dhikrAlhamdulillah: 'Alhamdulillah',
    dhikrAllahuAkbar: 'Allahu Akbar',
    dhikrAstaghfirullah: 'Astaghfirullah',
    dhikrLaIlaha: 'La ilaha illa Allah',
    challengeComplete: 'Mabrook! Challenge Complete',
    keepGoing: 'Keep Going',
    tapToCount: 'Tap to Recite',
    about: 'About Ibadathi',
    howItWorks: 'How it Works',
    guideTitle: 'Features Guide',
    appPurpose: 'Ibadathi is designed to be your spiritual companion, helping you stay consistent in your daily acts of worship.',
    fardGuide: 'Track your 5 daily obligatory prayers easily.',
    sunnahGuide: 'Mark optional Sunnah and Nawafil prayers.',
    qadahGuide: 'Automatically tracks missed prayers for makeup.',
    fastingGuide: 'Log your Ramadan and Sunnah fasts.',
    quranGuide: 'Track your Surah and Ayah progress.',
    womensGuide: 'Automated prayer exemption handling.',
    persistenceGuide: 'Secure access from any device with your login.',
    myAccount: 'My Account',
    logout: 'Log Out',
    consistency: 'Consistency Level',
    summary: 'Worship Summary',
    levelBeginner: 'Seeker',
    levelConsistent: 'Murid',
    levelAdvanced: 'Mumin',
    levelElite: 'Muhsin',
    profileDetails: 'Profile Details',
    addDhikr: 'Add Custom Dhikr',
    dhikrName: 'Dhikr Name',
    total: 'Total',
    daily: 'Daily',
    session: 'Session',
    resetSession: 'Reset Session',
    deleteDhikr: 'Delete Dhikr'
  },
  ar: {
    welcome: 'مرحباً بك',
    welcomeSub: 'مرحباً بك في عبادتي – رفيقك في العبادة',
    selectLanguage: 'اختر لغتك المفضلة',
    getStarted: 'ابدأ الآن',
    login: 'تسجيل الدخول',
    register: 'تسجيل جديد',
    username: 'اسم المستخدم',
    usernameAvailable: 'اسم المستخدم متاح',
    usernameTaken: 'اسم المستخدم محجوز مسبقاً',
    suggestions: 'اقتراحات:',
    name: 'الاسم الكامل',
    age: 'العمر',
    sex: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    place: 'المكان',
    password: 'كلمة المرور',
    language: 'الغة',
    home: 'الرئيسية',
    fard: 'الصلوات المفروضة',
    qadah: 'تقويم العبادة',
    sunnah: 'الصلوات المسنونة',
    fasting: 'تتبع الصيام',
    quran: 'تتبع القرآن',
    dhikr: 'عداد الأذكار',
    challenge: 'تحدي الأذكار',
    personal: 'أذكاري الخاصة',
    womensSpace: 'ركن المرأة',
    haydMode: 'وضع الحيض / النفاس',
    active: 'نشط',
    inactive: 'غير نشط',
    completed: 'تم',
    missed: 'فاتتني',
    excused: 'معذورة',
    pending: 'قيد الانتظار',
    save: 'حفظ',
    reset: 'إعادة ضبط',
    lastRead: 'آخر قراءة',
    surah: 'السورة',
    ayah: 'الآية',
    juz: 'الجزء',
    target: 'الهدف',
    progress: 'التقدم',
    missedPrayers: 'الصلوات الفائتة',
    back: 'الرجوع',
    hadithTitle: 'حديث اليوم',
    qibla: 'بوصلة القبلة',
    remembranceVerse: "ألا بذكر الله تطمئن القلوب",
    quranVirtue: "فضائل التلاوة",
    nextPrayer: 'الصلاة القادمة',
    notificationOn: 'التنبيهات مفعلة',
    notificationOff: 'التنبيهات معطلة',
    prayerAlertBody: 'حان وقت صلاة {prayer}.',
    prayerAlertTitle: 'تنبيه صلاة عبادتي',
    fajr: 'الفجر',
    dhuhr: 'الظهر',
    asr: 'العصر',
    maghrib: 'المغرب',
    isha: 'العشاء',
    todayPrayers: 'أوقات اليوم',
    qadaReminders: 'تنبيهات القضاء',
    addReminder: 'إضافة تنبيه',
    qadaAlertTitle: 'تنبيه صلاة القضاء',
    qadaAlertBody: 'حان الوقت لقضاء الصلوات الفائتة.',
    time: 'الوقت',
    reminders: 'التنبيهات',
    history: 'السجل',
    noHistory: 'لا يوجد سجل بعد',
    completeAndArchive: 'أرشفة التحدي',
    archiveSuccess: 'تمت أرشفة التحدي بنجاح!',
    markAllCompleted: 'تحديد الكل كمنجز',
    markAllMissed: 'تحديد الكل كفائت',
    dhikrList: 'التحديات النشطة',
    dhikrSalawat: 'الصلاة على النبي ﷺ',
    dhikrSubhanAllah: 'سبحان الله',
    dhikrAlhamdulillah: 'الحمد لله',
    dhikrAllahuAkbar: 'الله أكبر',
    dhikrAstaghfirullah: 'أستغفر الله',
    dhikrLaIlaha: 'لا إله إلا الله',
    challengeComplete: 'مبروك! اكتمل التحدي',
    keepGoing: 'استمر',
    tapToCount: 'انقر للذكر',
    about: 'حول عبادتي',
    howItWorks: 'كيف يعمل التطبيق',
    guideTitle: 'دليل الميزات',
    appPurpose: 'تم تصميم عبادتي ليكون رفيقك الروحي.',
    fardGuide: 'تتبع صلواتك الخمس اليومية المفروضة.',
    sunnahGuide: 'شجع نفسك مع صلوات السنن والنوافل.',
    qadahGuide: 'يحدد الصلوات الفائتة تلقائياً.',
    fastingGuide: 'سجل صيام رمضان والسنن.',
    quranGuide: 'تتبع تقدمك في السور والآيات.',
    womensGuide: 'تحديد تلقائي للأيام المعذورة.',
    persistenceGuide: 'بياناتك مرتبطة باسم المستخدم الخاص بك.',
    myAccount: 'حسابي',
    logout: 'تسجيل الخروج',
    consistency: 'مستوى الاستمرارية',
    summary: 'ملخص العبادة',
    levelBeginner: 'سالك',
    levelConsistent: 'مريد',
    levelAdvanced: 'مؤمن',
    levelElite: 'محسن',
    profileDetails: 'تفاصيل الملف الشخصي',
    addDhikr: 'إضافة ذكر جديد',
    dhikrName: 'اسم الذكر',
    total: 'المجموع',
    daily: 'اليومي',
    session: 'الجلسة',
    resetSession: 'إعادة الجلسة',
    deleteDhikr: 'حذف الذكر'
  },
  ml: {
    welcome: 'സ്വാഗതം',
    welcomeSub: 'ഇബാദത്തിയിലേക്ക് സ്വാഗതം - നിങ്ങളുടെ ആരാധനാ കൂട്ടാളി',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    getStarted: 'തുടങ്ങാം',
    login: 'ലോഗിൻ',
    register: 'രജിസ്റ്റർ',
    username: 'യൂസർ നെയിം',
    usernameAvailable: 'യൂസർനെയിം ലഭ്യമാണ്',
    usernameTaken: 'യൂസർനെയിം നിലവിലുണ്ട്',
    suggestions: 'നിർദ്ദേശങ്ങൾ:',
    name: 'മുഴുവൻ പേര്',
    age: 'പ്രായം',
    sex: 'ലിംഗം',
    male: 'പുരുഷൻ',
    female: 'സ്ത്രീ',
    place: 'സ്ഥലം',
    password: 'പാസ്‌വേഡ്',
    language: 'ഭാഷ',
    home: 'ഹോം',
    fard: 'ഫർദ് നിസ്കാരങ്ങൾ',
    qadah: 'ആരാധനാ കലണ്ടർ',
    sunnah: 'സുന്നത്ത് നിസ്കാരങ്ങൾ',
    fasting: 'നോമ്പ് ട്രാക്കർ',
    quran: 'ഖുർആൻ ട്രാക്കർ',
    dhikr: 'ദിക്ർ കൗണ്ടർ',
    challenge: 'ദിക്ർ ചലഞ്ച്',
    personal: 'വ്യക്തിഗത ദിക്റുകൾ',
    womensSpace: 'സ്ത്രീകളുടെ ഇടം',
    haydMode: 'ഹൈള് / നിഫാസ് മോഡ്',
    active: 'സജീവം',
    inactive: 'അസജീവം',
    completed: 'പൂർത്തിയായി',
    missed: 'നഷ്ടമായി',
    excused: 'ഒഴിവാക്കപ്പെട്ടു',
    pending: 'ബാക്കിയുണ്ട്',
    save: 'സേവ്',
    reset: 'റീസെറ്റ്',
    lastRead: 'അവസാനം വായിച്ചത്',
    surah: 'സൂറത്ത്',
    ayah: 'ആയത്ത്',
    juz: 'ജുസ്അ്',
    target: 'ലക്ഷ്യം',
    progress: 'പുരോഗതി',
    missedPrayers: 'നഷ്ടപ്പെട്ട നിസ്കാരങ്ങൾ',
    back: 'പിന്നിലേക്ക്',
    hadithTitle: 'ഇന്നത്തെ ഹദീസ്',
    qibla: 'ഖിബ്‌ല ഫൈൻഡർ',
    remembranceVerse: "അല്ലാഹുവെക്കുറിച്ചുള്ള ഓർമ്മകൊണ്ടാണ് ഹൃദയങ്ങൾ ശാന്തമാകുന്നത്.",
    quranVirtue: "ഖുർആൻ പാരായണത്തിന്റെ ഗുണങ്ങൾ",
    nextPrayer: 'അടുത്ത നിസ്കാരം',
    notificationOn: 'അറിയിപ്പുകൾ ഓൺ',
    notificationOff: 'അറിയിപ്പുകൾ ഓഫ്',
    prayerAlertBody: '{prayer} നിസ്കാരത്തിന് സമയമായി.',
    prayerAlertTitle: 'ഇബാദത്തി പ്രാർത്ഥന അറിയിപ്പ്',
    fajr: 'സുബ്ഹി',
    dhuhr: 'ളുഹർ',
    asr: 'അസർ',
    maghrib: 'മഗ്‌രിബ്',
    isha: 'ഇശാ',
    todayPrayers: 'ഇന്നത്തെ സമയങ്ങൾ',
    qadaReminders: 'ഖളാഅ് അറിയിപ്പുകൾ',
    addReminder: 'അറിയിപ്പ് ചേർക്കുക',
    qadaAlertTitle: 'ഖളാഅ് നിസ്കാര അറിയിപ്പ്',
    qadaAlertBody: 'നഷ്ടപ്പെട്ട നിസ്കാരങ്ങൾ വീട്ടുവാൻ സമയമായി.',
    time: 'സമയം',
    reminders: 'ഓർമ്മപ്പെടുത്തലുകൾ',
    history: 'ചരിത്രം',
    noHistory: 'ചരിത്രം ലഭ്യമല്ല',
    completeAndArchive: 'ചലഞ്ച് മാറ്റിവെക്കുക',
    archiveSuccess: 'ചലഞ്ച് വിജയകരമായി മാറ്റിവെച്ചു!',
    markAllCompleted: 'എല്ലാം പൂർത്തിയാക്കുക',
    markAllMissed: 'എല്ലാം നഷ്ടമായി',
    dhikrList: 'സജീവമായ ദിക്റുകൾ',
    dhikrSalawat: 'സ്വലാത്ത്',
    dhikrSubhanAllah: 'സ്വുബ്ഹാനള്ളാഹ്',
    dhikrAlhamdulillah: 'അൽഹംദുലില്ലാഹ്',
    dhikrAllahuAkbar: 'അല്ലാഹു അക്ബർ',
    dhikrAstaghfirullah: 'അസ്തഗ്ഫിറുള്ളാഹ്',
    dhikrLaIlaha: 'ലാ ഇലാഹ ഇല്ലല്ലാഹ്',
    challengeComplete: 'അൽഹംദുലില്ലാഹ്! ചലഞ്ച് പൂർത്തിയായി',
    keepGoing: 'തുടരുക',
    tapToCount: 'എണ്ണാൻ ക്ലിക്ക് ചെയ്യുക',
    about: 'ഇബാദത്തിയെക്കുറിച്ച്',
    howItWorks: 'പ്രവർത്തന രീതി',
    guideTitle: 'ഫീച്ചർ ഗൈഡ്',
    appPurpose: 'ആരാധനകളിൽ കൃത്യത പുലർത്താൻ സഹായിക്കുന്ന നിങ്ങളുടെ കൂട്ടാളി.',
    fardGuide: '5 നേരത്തെ നിസ്കാരങ്ങൾ ട്രാക്ക് ചെയ്യുക.',
    sunnahGuide: 'സുന്നത്ത് നിസ്കാരങ്ങൾ കൃത്യമായി നിർവഹിക്കാൻ.',
    qadahGuide: 'നഷ്ടപ്പെട്ട നിസ്കാരങ്ങൾ കണ്ടെത്താൻ.',
    fastingGuide: 'റമദാൻ നോമ്പും സുന്നത്ത് നോമ്പുകളും രേഖപ്പെടുത്താം.',
    quranGuide: 'ഖുർആൻ ഓതി നിർത്തിയ ഭാഗം രേഖപ്പെടുത്താം.',
    womensGuide: 'ഹൈള് സമയത്ത് നിസ്കാരങ്ങൾ ഒഴിവാക്കാൻ.',
    persistenceGuide: 'വിവരങ്ങൾ സുരക്ഷിതമായി സൂക്ഷിക്കപ്പെടുന്നു.',
    myAccount: 'എന്റെ അക്കൗണ്ട്',
    logout: 'ലോഗൗട്ട്',
    consistency: 'ക്രമബദ്ധത ലെവൽ',
    summary: 'ആരാധന സംഗ്രഹം',
    levelBeginner: 'സീക്കർ',
    levelConsistent: 'മുരീദ്',
    levelAdvanced: 'മുഅ്മിൻ',
    levelElite: 'മുഹ്സിൻ',
    profileDetails: 'പ്രൊഫൈൽ വിവരങ്ങൾ',
    addDhikr: 'പുതിയ ദിക്ർ ചേർക്കുക',
    dhikrName: 'പേര്',
    total: 'ആകെ',
    daily: 'ഇന്ന്',
    session: 'ഇപ്പോൾ',
    resetSession: 'റീസെറ്റ്',
    deleteDhikr: 'ഡിലീറ്റ്'
  },
  ta: {
    welcome: 'வரவேற்பு',
    welcomeSub: 'இபாதத்திக்கு வரவேற்கிறோம் - உங்கள் வழிபாட்டுத் துணை',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    getStarted: 'தொடங்குவோம்',
    login: 'உள்நுழை',
    register: 'பதிவு செய்',
    username: 'பயனர் பெயர்',
    usernameAvailable: 'பயனர் பெயர் கிடைக்கிறது',
    usernameTaken: 'பயனர் பெயர் ஏற்கனவே உள்ளது',
    suggestions: 'பரிந்துரைகள்:',
    name: 'முழு பெயர்',
    age: 'வயது',
    sex: 'பாலினம்',
    male: 'ஆண்',
    female: 'பெண்',
    place: 'இடம்',
    password: 'கடவுச்சொல்',
    language: 'மொழி',
    home: 'முகப்பு',
    fard: 'ஃபர்ளு தொழுகைகள்',
    qadah: 'வழிபாட்டு காலண்டர்',
    sunnah: 'சுன்னத் தொழுகைகள்',
    fasting: 'நோன்பு கண்காணிப்பு',
    quran: 'குர்ஆன் கண்காணிப்பு',
    dhikr: 'திக்ர் கவுண்டர்',
    challenge: 'திக்ர் சவால்',
    personal: 'தனிப்பட்ட திக்ர்',
    womensSpace: 'பெண்களுக்கான இடம்',
    haydMode: 'ஹைழ் / நிஃபாஸ் முறை',
    active: 'செயலில்',
    inactive: 'செயலற்றது',
    completed: 'முடிந்தது',
    missed: 'தவறியது',
    excused: 'விலக்கு',
    pending: 'நிலுவையில்',
    save: 'சேமி',
    reset: 'மீட்டமை',
    lastRead: 'கடைசியாக வாசித்தது',
    surah: 'சூரா',
    ayah: 'வசனம்',
    juz: 'ஜுஸ்',
    target: 'இலக்கு',
    progress: 'முன்னேற்றம்',
    missedPrayers: 'தவறிய தொழுகைகள்',
    back: 'பின்செல்',
    hadithTitle: 'இன்றைய ஹதீஸ்',
    qibla: 'கிப்லா திசை காட்டி',
    remembranceVerse: "நிச்சயமாக அல்லாஹ்வை நினைவுகூர்வதன் மூலமே இதயங்கள் அமைதியடைகின்றன.",
    quranVirtue: "குர்ஆன் ஓதுவதன் சிறப்புகள்",
    nextPrayer: 'அடுத்த தொழுகை',
    notificationOn: 'அறிவிப்புகள் ஆன்',
    notificationOff: 'அறிவிப்புகள் ஆஃப்',
    prayerAlertBody: '{prayer} தொழுகைக்கு நேரமாகிவிட்டது.',
    prayerAlertTitle: 'இபாதத்தி தொழுகை அறிவிப்பு',
    fajr: 'ஃபஜ்ர்',
    dhuhr: 'ளுஹர்',
    asr: 'அஸர்',
    maghrib: 'மக்ரிப்',
    isha: 'இஷா',
    todayPrayers: 'இன்றைய நேரங்கள்',
    qadaReminders: 'களா அறிவிப்புகள்',
    addReminder: 'அறிவிப்பைச் சேர்',
    qadaAlertTitle: 'களா தொழுகை அறிவிப்பு',
    qadaAlertBody: 'தவறிய தொழுகைகளைத் தொழுவதற்கான நேரம்.',
    time: 'நேரம்',
    reminders: 'நினைவூட்டல்கள்',
    history: 'வரலாறு',
    noHistory: 'வரலாறு இல்லை',
    completeAndArchive: 'சவாலைச் சேமிக்கவும்',
    archiveSuccess: 'சவால் வெற்றிகரமாகச் சேமிக்கப்பட்டது!',
    markAllCompleted: 'அனைத்தையும் முடிக்கவும்',
    markAllMissed: 'அனைத்தும் தவறவிட்டது',
    dhikrList: 'திக்ர் சவால்கள்',
    dhikrSalawat: 'ஸலவாத்',
    dhikrSubhanAllah: 'சுபஹானல்லாஹ்',
    dhikrAlhamdulillah: 'அல்ஹம்துலில்லாஹ்',
    dhikrAllahuAkbar: 'அல்லாஹு அகபர்',
    dhikrAstaghfirullah: 'அஸ்தஃபிருல்லாஹ்',
    dhikrLaIlaha: 'லா இலாஹ இல்லல்லாஹ்',
    challengeComplete: 'அல்ஹம்துலில்லாஹ்! முடிந்தது',
    keepGoing: 'தொடரவும்',
    tapToCount: 'எண்ணத் தொடங்குங்கள்',
    about: 'இபாதத்தி பற்றி',
    howItWorks: 'செயல்முறை',
    guideTitle: 'அம்சங்கள் வழிகாட்டி',
    appPurpose: 'உங்கள் அன்றாட வழிபாடுகளில் நிலைத்திருக்க உதவுகிறது.',
    fardGuide: 'ஃபர்ளு தொழுகைகளைக் கண்காணிக்கவும்.',
    sunnahGuide: 'சுன்னத் தொழுகைகளை நிறைவேற்ற ஊக்குவிக்கிறது.',
    qadahGuide: 'தவறிய தொழுகைகளைத் தானாகக் கண்டறியும்.',
    fastingGuide: 'நோன்புகளைப் பதிவு செய்யுங்கள்.',
    quranGuide: 'குர்ஆன் முன்னேற்றத்தைக் கண்காணிக்கவும்.',
    womensGuide: 'தொழுகைகளை விலக்கு என்று அடையாளப்படுத்தும்.',
    persistenceGuide: 'தகவல்கள் பாதுகாப்பாக இணைக்கப்பட்டுள்ளன.',
    myAccount: 'எனது கணக்கு',
    logout: 'வெளியேறு',
    consistency: 'நிலைத்தன்மை நிலை',
    summary: 'வழிபாட்டு சுருக்கம்',
    levelBeginner: 'தேடுபவர்',
    levelConsistent: 'முரீது',
    levelAdvanced: 'முஃமின்',
    levelElite: 'முஹ்சின்',
    profileDetails: 'சுயவிவர விவரங்கள்',
    addDhikr: 'புதிய திக்ர் சேர்க்கவும்',
    dhikrName: 'பெயர்',
    total: 'மொத்தம்',
    daily: 'இன்று',
    session: 'அமர்வு',
    resetSession: 'மீட்டமை',
    deleteDhikr: 'நீக்கு'
  }
};